### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by huoyaoyuan** [huoyaoyuan/AdmiralRoom#4]
- [ ] 从logbook导入
- [ ] 出击统计、战斗详情记录
- [ ] 舰队详情窗口、属性计算
- [x] 图标
- [x] 配色
- [x] resx->DynamicResource
- [x] 关闭窗口确认
- [x] 使用代理进行更新

**Comment by awp9835** [comment]
- 关闭前确认

_"你远征忘了放"
"你远征马上就能收了"(10min)
"你今天的任务做完了吗?"(可以只是这句话)
"你还有船没修"(MDZZ)"
较上次退出时的资源变化_
- "舰队""战况"”司令部“等页面需要自动适应分辨率,不然实在是太大了
- 一键布局
- 锁定/解锁 "浏览器"的滚动条(迷之去不掉时)
- ”开发“：新出的装备应该放在上面
- 远征条件查询;显示未接任务;经验计算
- 实时提醒(可以设置是否开启单项功能)

_没接任务
大破
新出的船和稀有船锁定提示
 船位和装备满了
忘带装备（MDZZ）
远征不符合条件_
- 老板键

**Comment by Blealtan** [comment]
“你今天的任务做完了吗？”

一股战舰世界味。。

**Comment by Blealtan** [comment]
Re @awp9835 :

“你今天的任务做完了吗？”

一股战舰世界味。。

**Comment by awp9835** [comment]
_AdmiralRoom/AdmiralRoom/KanColleBrowser.xaml.cs_
这里面_private void ApplyStyleSheet_和_public bool TakeScreenShot_中检测游戏flash界面的代码
只能检测url中含有“.swf?"或HTML中flash界面ID为 "game_frame"的游戏网页
一些缓存系统（ooi）和直连网站，可能并不具备上述特征
- 建议修改为 “game_frame"如果测不到,再检测有没有"ooi-game"或"flashWrap“
  这两个ID对应的组件与"game_frame"性质几乎相同但是有"embed"

**Comment by Blealtan** [comment]
能否提供更详细的信息？我有一个想法是利用游戏画面大小800*480的特性，解析DOM树寻找符合特性的最小元素并予以显示。如果您所说的ooi和直连站也有这种特征，我想是可行的。

**Comment by awp9835** [comment]
我想说的是
还有一种方法是寻找游戏界面的左边界和上边界

**Comment by awp9835** [comment]
退出前确认出了点问题,点退出会直接崩掉
浏览器的前进和后退按钮  滞后了一步

**Comment by huoyaoyuan** [comment]
改用看板管理TODO List。
