### ISSUE TITLE
Incorrect drop-ship reporting

### ISSUE THREAD

**Issue by Gizeta** [huoyaoyuan/AdmiralRoom#6]
PoiDBReporter 提交的数据存在一些错误：
shipId 部分为 0（文档中未掉落为 -1）
enemyShips 未过滤掉 api 中起始的 -1（见 poooi/poi-server/issues/9）

为了不会干扰到其他使用数据库的开发者，建议修复并更新提交 UA 的版本号。
（实际在 poi-statistics 这里 AdmiralRoom 提交的数据因为不符合规范都被过滤掉了）

**Comment by Gizeta** [comment]
另外补充一句，处理 6-5 联合舰队的 enemyShips，直接把一队二队的敌舰 id 合并成一个长度 12 的数组即可（poi 的插件那边还没更新，目前讨论是这样）。

**Comment by huoyaoyuan** [comment]
关于shipId的0：我记得曾经在讨论时说过，使用不同的数字来区分未掉落和船位已满的情况

**Comment by Gizeta** [comment]
原来是这样的考虑呀。不过实际其他插件实现的时候都是没有考虑船位已满的情况。
（我印象中 poi 那边的态度是不考虑船位情况的吧）

**Comment by huoyaoyuan** [comment]
已经按照最新的document进行了修正。目前测试使用的UA是`AdmiralRoom Reporter v2 Test`，可以先确认一下数据，没有问题的话我就改为`AdmiralRoom Reporter v2`并合并进Release。

**Comment by Gizeta** [comment]
嗯。已经没有问题了。
Thanks
